### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by arudd20** [richardW8k/enablegfpaymentdetails#2]
I'm using Stripe Add-On for Payments.

After installing and activating the plugin, I'm not finding a way to edit the Payment Details.

The plugin was last updated over a year ago.

WP - Version 4.9.8
Gravity Forms - Version 2.3.3
Stripe - Version 2.5

**Comment by bluantinoo** [comment]
I'm using both Stripe and Paypal standard addons, and it works.

WP - Version 4.9.8
Gravity Forms - Version 2.3.3
Stripe - Version 2.5

**Comment by Mascaren-da-Gonozal** [comment]
I am using The Paypal add-on 
WP - 5.1.1
GF - 2.4.8
PP Standard 3.1
I can change the values, but its not stored when updating. Any help is appreciated as I also offer  "Bank transfer" as an option and like to be able to set the Status to paid.

**Comment by astrod00d** [comment]
I am also using the Paypal add-on and sometime in the last month it seems to have stop allowing me to update from Processing to Paid.  It just reverts back when I click Update.
WP - 5.2.1
GF - 2.4.10
PP Standard 3.1
